#pragma once

#define WORLD_SPEED 2

enum WORLD_CHARACTER_STATE
{
	//월드맵 케릭터 상태
	WORLD_EAST_IDLE,			//동쪽 IDLE
	WORLD_EAST_MOVE,			//동쪽 이동
	WORLD_WEST_IDLE,			//서쪽 IDLE
	WORLD_WEST_MOVE,			//서쪽 이동
	WORLD_NORTH_IDLE,			//북쪽 IDLE
	WORLD_NORTH_MOVE,			//북쪽 이동
	WORLD_SOUTH_IDLE,			//남쪽 IDLE
	WORLD_SOUTH_MOVE,			//남쪽 이동
	WORLD_NORTH_EAST_IDLE,		//북동 IDLE
	WORLD_NORTH_EAST_MOVE,		//북동 이동
	WORLD_NORTH_WEST_IDLE,		//북서 IDLE
	WORLD_NORTH_WEST_MOVE,		//북서 이동
	WORLD_SOUTH_EAST_IDLE,		//남동 IDLE
	WORLD_SOUTH_EAST_MOVE,		//남동 이동
	WORLD_SOUTH_WEST_IDLE,		//남서 IDLE
	WORLD_SOUTH_WEST_MOVE,		//남서 이동
};

enum WORLD_MAKE_BRIDGE
{
	//다리 만드는 액션 상태
	NOTHING_TO_DO,
	JAKE_HORIZONTAL_MOVE,
	JAKE_VERTICAL_MOVE,
	JAKE_MAKE_BRIDGE,
	FINN_HORIZONTAL_MOVE,
	FINN_VERTICAL_MOVE,
	JAKE_REMOVE_BRIDGE,
	JAKE_SET_POSITION
};